### ISSUE TITLE
SFDX project detection

### ISSUE THREAD

**Issue by aranwe** [drossi750/vscode-salesforce-toolkit#18]
Hi,

enabling this extension by checking the presence of `force-app` directory is not such a good idea as it can be any other directory. (i.e. `src`)

I propose to check for presence of `sfdx-project.json` and using the path from package in `packageDirectories` with `"default": true` :)

Thank you!
Cheers

**Comment by drossi750** [comment]
Hi, it's a good idea to make it more flexible indeed. You can contribute also directly to the code, I am swamped.

**Comment by drossi750** [comment]
PR #21 merged, bumped to 1.3.0 and published. 
Thanks for contributing :)

**Comment by aranwe** [comment]
Glad to help, never played with vscode extension, it was nice to see the internals :)
