### ISSUE TITLE
Icons are not loading 

### ISSUE THREAD

**Issue by oleg-underscore-r** [drossi750/vscode-salesforce-toolkit#8]
<img width="289" alt="Screen Shot 2021-05-08 at 9 40 50 AM" src="https://user-images.githubusercontent.com/2013992/117543283-c0147280-afe1-11eb-8ea2-a9c6d8b687bb.png">

**Comment by drossi750** [comment]
Hi @oleg-underscore-r , I am trying to reproduce, did a fresh install on a Windows 10 machine with:

Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

And it doesn't look bad. Can you give me more details about your environment?

**Comment by drossi750** [comment]
can't reproduce
